# site settings
title: Shuyu's Repo
subtitle: by Shuyu
email: shuyuwang123@gmail.com
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Monterey Park
state: CA
zip_code: 91755
country: United States of America
phone: (314) 555-5555

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://treeforest456.github.io
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/shuyuwangwiredin/
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
